### PR TITLE
macOS

### PR DESCRIPTION
**Pull request by bencevans**
⚠️ GPT Generated Description...

This PR introduces significant improvements to the `GameboyEmulator` project by integrating the SDL2 library and enhancing platform compatibility through the adjustment of linker flags. These changes aim to streamline the development process across different operating systems and leverage SDL2's capabilities for a more robust emulation experience.

#### Key Changes:
- **SDL2 Integration:** The SDL2 library has been added to the project to replace the previously considered SFML library. This change is facilitated through the modification of the `CMakeLists.txt` file to find and include the SDL2 library and its directories. This integration enables the use of SDL2's extensive features for handling graphics, sound, and input devices, which are crucial for emulating Gameboy games accurately.

- **Platform-Specific Linker Flags:** We have introduced conditional statements in the `CMakeLists.txt` file to adjust the linker flags based on the operating system. Specifically, for UNIX systems that are not macOS, the linker flag `-Wl,--copy-dt-needed-entries` is set to ensure proper dynamic linking. This adjustment enhances the compatibility and performance of the emulator on various platforms.

- **Documentation Updates:** A new `README.md` file has been added to guide users through the installation process on Ubuntu/Debian and macOS. This document includes step-by-step instructions for installing the necessary dependencies, such as `cmake` and `libsdl2-dev`, and compiling the emulator. The addition of this README aims to improve the user experience by providing clear and concise setup instructions.

#### Technical Details:
- The `find_package` command is utilized to locate the SDL2 library, and the `include_directories` command is adjusted to include SDL2's header files.
- The `CMAKE_EXE_LINKER_FLAGS` and `CMAKE_CXX_FLAGS` are configured to ensure the code complies with strict standards (`-Wall -Werror`) and is compatible with C++11.
- The source directory and file compilation process have been streamlined to enhance clarity and maintainability.

This PR represents a strategic move to enhance the `GameboyEmulator` project's functionality and user experience across different operating systems. By adopting SDL2 and refining the build process, we aim to provide a solid foundation for further development and improvements to the emulator.

### CODE REVIEW

**Comment by MatthewJohn** [comment]
I mean... does this work? It didn't work very well when I was trying to get it to work! :laughing:

Did chatgpt make the changes, or does it actually build? :lab_coat: 

Keeping in mind, you're editing a file who's last commit (https://github.com/MatthewJohn/GameboyEmulator/commit/07dc45a2fa7242bdced75918843d5e874384679c) had the message "Move to SDL2 and don't look back!"

**Comment by bencevans** [comment]
Haha, I made the changes but ChatGPT did the description based on the git patch. It builds but it didn't run the ROM. Something to do with ticks not set for the op.

**Comment by MatthewJohn** [comment]
> Haha, I made the changes but ChatGPT did the description based on the git patch. It builds but it didn't run the ROM. Something to do with ticks not set for the op.

Which ROM did you use?

Probably irrelevant of the fact, but 99.99% ROMs won't work :P

**Comment by bencevans** [comment]
Screenshot 2024-02-26 at 18 06 29

ah missing opcode

**Comment by MatthewJohn** [comment]
> Screenshot 2024-02-26 at 18 06 29
> 
> ah missing opcode

I've merged the PR :)

So, it's unlikely to be a missing op-code - all of them are (or at least as far as I remember).. what is most likely that they just don't work, as such, based on what I've seen:
 * the sub commands appears to have the most bugs, so, maybe:
 * some value got subtracted incorrectly, then
 * it tried to jump to the value
 * the new value at the new PC was actually meant to be data and not a valid opcode
:)

**Comment by MatthewJohn** [comment]
This was merged in: https://github.com/MatthewJohn/GameboyEmulator/commit/240e03168be03e76ca3e160ad5456d55e8b03dd9

**Pull request closed without merging**
